[package]
authors = ["Frederic Dumont <fdumontmd@gmail.com>"]
name = "cask-update"
version = "0.4.1"
publish = false

[dependencies]
error-chain = "0.11.0"
regex = "1"
structopt = "0.2"
structopt-derive = "0.2"
tabwriter = "1"
